### ISSUE TITLE
parameterisation of bash scripts

### ISSUE THREAD

**Issue by sergiomaffeis** [euangoodbrand/Learning_From_Noisy_NIDS_Data#1]
would be nice to parameterise the loop further, not only on the variable used here, but on the other ones as well.
ideally there could be only one, or a few "template python commands" instead of ~100 lines of them :)
(just being a bit OCD about it)

https://github.com/euangoodbrand/Learning_From_Noisy_NIDS_Data/blob/9579b3615e7c8fa6bcab42f464076c9b7589c4c6/CoTeaching/coTeaching.sh#L5

**Comment by euangoodbrand** [comment]
Of course, done.
